In [189]:
import numpy as np
import pandas as pd
from category_encoders import TargetEncoder
from sklearn.model_selection import GroupKFold, train_test_split
from sklearn.preprocessing import RobustScaler, StandardScaler, OneHotEncoder
from sklearn.decomposition import PCA
from sklearn.pipeline import Pipeline

In [190]:
def month_encoded(df: pd.DataFrame):
    df['month_sin'] = np.sin(2 * np.pi * df['Месяц'] / 12)
    df['month_cos'] = np.cos(2 * np.pi * df['Месяц'] / 12)

    df.drop(columns=['Месяц'], inplace=True)
    
    return df

In [191]:
def robust_encoded(df_train: pd.DataFrame, df_test: pd.DataFrame):
    mask_traffic = [
        'Численность населения',
        'Количество домохозяйств',
        'Трафик пеший, в час',
        'Трафик авто, в час',
        'Населенный пункт_fold_traffic',
        'Регион_fold_traffic'
    ]
    mask_average_bill = [
        'Численность населения',
        'Количество домохозяйств',
        'Трафик пеший, в час',
        'Трафик авто, в час',
        'Населенный пункт_fold_average_bill',
        'Регион_fold_average_bill'
    ]

    rs = RobustScaler()
    if 'Населенный пункт_fold_traffic' in df_train.columns and 'Регион_fold_traffic' in df_train.columns:
        df_train[mask_traffic] = rs.fit_transform(df_train[mask_traffic])
        df_test[mask_traffic] = rs.transform(df_test[mask_traffic])
    elif 'Населенный пункт_fold_average_bill' in df_train.columns and 'Регион_fold_average_bill' in df_train.columns:
        df_train[mask_average_bill] = rs.fit_transform(df_train[mask_average_bill])
        df_test[mask_average_bill] = rs.transform(df_test[mask_average_bill])

    return df_train, df_test

In [192]:
def pca_applied(df_train: pd.DataFrame, df_test: pd.DataFrame):
    counts = [
        'Маркетплейсы, доставки, постаматы (100 м)',
        'Медицинские уч. и аптеки (300 м)',
        'Школы (300 м)',
        'Остановки (300 м)',
        'Продуктовые магазины (500 м)',
        'Пятерочки (500 м)'
    ]
    pca_param = df_train[counts]

    pca_param_train, pca_param_test = train_test_split(pca_param, test_size=0.3, random_state=598)
    pipeline = Pipeline([('scaler', StandardScaler()),('pca', PCA(n_components=4, random_state=598))])

    pipeline.fit(pca_param_train)

    pca_train = pipeline.transform(df_train.iloc[pca_param_train.index][counts])
    pca_train_valid = pipeline.transform(df_train.iloc[pca_param_test.index][counts])
    pca_test = pipeline.transform(df_test[counts])

    print(f'Доля объясненной дисперсии: {sum(pipeline.named_steps['pca'].explained_variance_ratio_)}')

    pca_train_df = pd.DataFrame(
        np.vstack([pca_train, pca_train_valid]),
        columns=['pca_1', 'pca_2', 'pca_3', 'pca_4'],
        index=np.concatenate([pca_param_train.index, pca_param_test.index])
    ).sort_index()
    pca_test_df = pd.DataFrame(
        pca_test,
        columns=['pca_1', 'pca_2', 'pca_3', 'pca_4']
    )

    df_train = pd.concat([df_train, pca_train_df], axis=1)
    df_test = pd.concat([df_test, pca_test_df], axis=1)

    df_train.drop(columns=counts, inplace=True)
    df_test.drop(columns=counts, inplace=True)

    return df_train, df_test

In [193]:
def target_encoder_traffic_avg_bill(df_train: pd.DataFrame, df_test: pd.DataFrame):
    df_train['Населенный пункт_fold_traffic'] = np.nan
    df_train['Регион_fold_traffic'] = np.nan
    df_train['Населенный пункт_fold_average_bill'] = np.nan
    df_train['Регион_fold_average_bill'] = np.nan

    encoders_traffic = []
    encoders_average_bill = []

    gkf = GroupKFold(n_splits=5)

    for train_id, validation_id in gkf.split(df_train, groups=df_train['new_id']):
    
        X_train = df_train.iloc[train_id][['Населенный пункт', 'Регион']]
        X_validation = df_train.iloc[validation_id][['Населенный пункт', 'Регион']]
        y_train_traffic = df_train.iloc[train_id]['Трафик']
        y_train_average_bill = df_train.iloc[train_id]['Средний чек']
        
        TE_traffic = TargetEncoder(cols = ['Населенный пункт', 'Регион'], smoothing = 20)
        TE_traffic.fit(X_train, y_train_traffic)
        val_traffic = TE_traffic.transform(X_validation)
        encoders_traffic.append(TE_traffic)
        
        df_train.iloc[validation_id, df_train.columns.get_loc('Населенный пункт_fold_traffic')] = val_traffic['Населенный пункт']
        df_train.iloc[validation_id, df_train.columns.get_loc('Регион_fold_traffic')] = val_traffic['Регион']
        
        TE_average_bill = TargetEncoder(cols = ['Населенный пункт', 'Регион'], smoothing = 20)
        TE_average_bill.fit(X_train, y_train_average_bill)
        val_average_bill = TE_average_bill.transform(X_validation)
        encoders_average_bill.append(TE_average_bill)
        
        df_train.iloc[validation_id, df_train.columns.get_loc('Населенный пункт_fold_average_bill')] = val_average_bill['Населенный пункт']
        df_train.iloc[validation_id, df_train.columns.get_loc('Регион_fold_average_bill')] = val_average_bill['Регион']
    
    encoded_sum_traffic_df_test = None
    encoded_sum_average_bill_df_test = None

    for traffic_encoder in encoders_traffic:
        encoded = traffic_encoder.transform(df_test[['Населенный пункт', 'Регион']])
        if encoded_sum_traffic_df_test is None:
            encoded_sum_traffic_df_test = encoded
        else:
            encoded_sum_traffic_df_test += encoded
    
    for average_bill_encoder in encoders_average_bill:
        encoded = average_bill_encoder.transform(df_test[['Населенный пункт', 'Регион']])
        if encoded_sum_average_bill_df_test is None:
            encoded_sum_average_bill_df_test = encoded
        else:
            encoded_sum_average_bill_df_test += encoded
    
    df_test_traffic_encoded =  encoded_sum_traffic_df_test / len(encoders_traffic)
    df_test_average_bill_encoded = encoded_sum_average_bill_df_test / len(encoders_average_bill)

    df_train_traffic = df_train.drop(
        columns=[
            'Средний чек',
            'Населенный пункт_fold_average_bill',
            'Регион_fold_average_bill',
            'Населенный пункт',
            'Регион'
        ]
    )
    df_train_average_bill = df_train.drop(
        columns=[
            'Трафик',
            'Населенный пункт_fold_traffic',
            'Регион_fold_traffic',
            'Населенный пункт',
            'Регион'
        ]
    )

    df_test_traffic = df_test.copy()
    df_test_traffic[['Населенный пункт_fold_traffic', 'Регион_fold_traffic']] = df_test_traffic_encoded
    df_test_traffic.drop(columns=['Населенный пункт', 'Регион'], inplace=True)

    df_test_average_bill = df_test.copy()
    df_test_average_bill[['Населенный пункт_fold_average_bill', 'Регион_fold_average_bill']] = df_test_average_bill_encoded
    df_test_average_bill.drop(columns=['Населенный пункт', 'Регион'], inplace=True)

    return df_train_traffic, df_train_average_bill, df_test_traffic, df_test_average_bill

In [194]:
def ohe_encoded(df_train: pd.DataFrame, df_test: pd.DataFrame):
    categorical_features = ['Дата открытия, категориальный', 'Торговая площадь, категориальный']

    ohe = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

    df_train_ohe = ohe.fit_transform(df_train[categorical_features]).astype(int)
    df_test_ohe = ohe.transform(df_test[categorical_features]).astype(int)

    df_train[ohe.get_feature_names_out(categorical_features)] = df_train_ohe
    df_test[ohe.get_feature_names_out(categorical_features)] = df_test_ohe

    df_train.drop(columns=categorical_features, inplace=True)
    df_test.drop(columns=categorical_features, inplace=True)

    return df_train, df_test

In [195]:
df_train = pd.read_csv('../data/X5_after_eda.csv')
df_test = pd.read_csv('../data/result_test_df.csv')
df_train.head()

,new_id,Месяц,Трафик,Средний чек,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м)
0,0,10,59662,823.060390,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.9,200.333333,0,6,0,0,2,0
1,0,5,56674,859.361975,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.9,200.333333,0,6,0,0,2,0
2,0,1,51488,763.937766,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.9,200.333333,0,6,0,0,2,0
3,0,6,56693,836.362309,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.9,200.333333,0,6,0,0,2,0
4,0,7,58128,845.257709,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.9,200.333333,0,6,0,0,2,0

In [196]:
df_train = month_encoded(df_train)
df_test = month_encoded(df_test)

df_test.drop(columns=['Полный адрес помещения', 'url', 'Торговая площадь, вещественный'], inplace=True)

df_train, df_test = pca_applied(df_train, df_test)
df_train_traffic, df_train_average_bill, df_test_traffic, df_test_average_bill = target_encoder_traffic_avg_bill(df_train, df_test)
df_train_traffic, df_test_traffic = ohe_encoded(df_train_traffic, df_test_traffic)
df_train_average_bill, df_test_average_bill = ohe_encoded(df_train_average_bill, df_test_average_bill)
df_train_traffic, df_test_traffic = robust_encoded(df_train_traffic, df_test_traffic)
df_train_average_bill, df_test_average_bill = robust_encoded(df_train_average_bill, df_test_average_bill)

df_train_traffic.drop(columns=['new_id'], inplace=True)
df_train_average_bill.drop(columns=['new_id'], inplace=True)

df_train_traffic.head()

Доля объясненной дисперсии: 0.8483389629854581

,Трафик,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час",month_sin,month_cos,pca_1,pca_2,pca_3,pca_4,Населенный пункт_fold_traffic,Регион_fold_traffic,"Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
0,59662,-0.183291,-0.634931,-0.658506,0.29525,-8.660254e-01,0.500000,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
1,56674,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
2,51488,-0.183291,-0.634931,-0.658506,0.29525,5.000000e-01,0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
3,56693,-0.183291,-0.634931,-0.658506,0.29525,1.224647e-16,-1.000000,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1
4,58128,-0.183291,-0.634931,-0.658506,0.29525,-5.000000e-01,-0.866025,-0.647364,0.219085,0.058661,-1.24818,-0.273791,-0.09916,0,0,1,0,0,0,1

In [197]:
df_train_traffic.to_csv('../data/df_train_traffic_encoded_scaled.csv', index=False, encoding='utf-8')
df_test_traffic.to_csv('../data/df_test_traffic_encoded_scaled.csv', index=False, encoding='utf-8')
df_train_average_bill.to_csv('../data/df_train_average_bill_encoded_scaled.csv', index=False, encoding='utf-8')
df_test_average_bill.to_csv('../data/df_test_average_bill_encoded_scaled.csv', index=False, encoding='utf-8')