In [20]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
from catboost import CatBoostRegressor
from sklearn.linear_model import Ridge
import plotly.express as px

In [10]:
train_traffic = pd.read_csv('../data/df_train_traffic_encoded_scaled.csv')
train_average_bill = pd.read_csv('../data/df_train_average_bill_encoded_scaled.csv')

X_train_traffic = train_traffic.drop(columns=['Трафик'])
y_train_traffic = train_traffic['Трафик']

X_train_average_bill = train_average_bill.drop(columns=['Средний чек'])
y_train_average_bill = train_average_bill['Средний чек']

X_train_traffic, X_val_traffic, y_train_traffic, y_val_traffic = train_test_split(X_train_traffic, y_train_traffic, test_size=0.3, random_state=598)
X_train_train_traffic, X_train_test_traffic, y_train_train_traffic, y_train_test_traffic = train_test_split(X_train_traffic, y_train_traffic, test_size=0.28, random_state=598)

X_train_average_bill, X_val_average_bill, y_train_average_bill, y_val_average_bill = train_test_split(X_train_average_bill, y_train_average_bill, test_size=0.3, random_state=598)
X_train_train_average_bill, X_train_test_average_bill, y_train_train_average_bill, y_train_test_average_bill = train_test_split(X_train_average_bill, y_train_average_bill, test_size=0.28, random_state=598)

In [11]:
def metrics_compare(model, model_name, target):
    
    model_rmse = 0
    model_mae = 0

    if target == 'Трафик':

        model.fit(X_train_train_traffic, y_train_train_traffic)

        model_rmse = np.sqrt(mean_squared_error(y_train_test_traffic, model.predict(X_train_test_traffic)))
        model_mae = mean_absolute_error(y_train_test_traffic, model.predict(X_train_test_traffic))

    elif target == 'Средний чек':

        model.fit(X_train_train_average_bill, y_train_train_average_bill)

        model_rmse = np.sqrt(mean_squared_error(y_train_test_average_bill, model.predict(X_train_test_average_bill)))
        model_mae = mean_absolute_error(y_train_test_average_bill, model.predict(X_train_test_average_bill))

    model_metrics = pd.DataFrame({
        'Целевая переменная' : [target],
        'Модель' : [model_name],
        'RMSE' : [model_rmse],
        'MAE' : [model_mae]
    })

    return model_metrics

## Трафик

In [12]:
rf_best_params_traffic = {
    'n_estimators': [1000],
    'max_depth': [60],
    'max_features': [0.8],
    'max_samples': [1.0]
}

In [13]:
mlp_metrics_traffic = pd.DataFrame({
    'Целевая переменная' : ['Трафик'],
    'Модель' : ['MLP'],
    'RMSE' : [5605.07],
    'MAE' : [4021.38]
})
mlp_metrics_traffic

  Целевая переменная Модель     RMSE      MAE
0             Трафик    MLP  5605.07  4021.38

In [14]:
ridge_metrics_traffic = metrics_compare(
    Ridge(alpha=1.0),
    'RidgeRegression',
    'Трафик'
)

knn_metrics_traffic = metrics_compare(
    KNeighborsRegressor(n_neighbors=1, n_jobs=-1),
    'KNN',
    'Трафик'
)

rf_metrics_traffic = metrics_compare(
    RandomForestRegressor(
        max_depth=60,
        max_features=0.8,
        max_samples=1.0,
        n_estimators=1000,
        random_state=598
    ),
    'RandomForest',
    'Трафик'
)

catboost_metrics_traffic = metrics_compare(
    CatBoostRegressor(learning_rate=0.05, l2_leaf_reg=1, iterations=500, depth=10, random_state=1337),
    'CATBOOST',
    'Трафик'
)

0:	learn: 13159.3617566	total: 35.8ms	remaining: 17.8s
1:	learn: 12898.6730812	total: 49.4ms	remaining: 12.3s
2:	learn: 12660.9376491	total: 59.3ms	remaining: 9.83s
3:	learn: 12438.6187988	total: 76.3ms	remaining: 9.47s
4:	learn: 12232.7403967	total: 85.1ms	remaining: 8.43s
5:	learn: 12044.0050064	total: 93.9ms	remaining: 7.73s
6:	learn: 11868.6926380	total: 102ms	remaining: 7.21s
7:	learn: 11706.9420393	total: 112ms	remaining: 6.86s
8:	learn: 11554.8218567	total: 121ms	remaining: 6.58s
9:	learn: 11412.9152828	total: 129ms	remaining: 6.34s
10:	learn: 11279.9147564	total: 138ms	remaining: 6.13s
11:	learn: 11158.5499265	total: 146ms	remaining: 5.95s
12:	learn: 11047.8821321	total: 154ms	remaining: 5.78s
13:	learn: 10942.9744644	total: 163ms	remaining: 5.64s
14:	learn: 10847.7058259	total: 171ms	remaining: 5.53s
15:	learn: 10758.8438513	total: 180ms	remaining: 5.44s
16:	learn: 10675.1485484	total: 189ms	remaining: 5.36s
17:	learn: 10598.2701384	total: 198ms	remaining: 5.29s
18:	learn: 10525.4177664	total: 206ms	remaining: 5.22s
19:	learn: 10458.7726924	total: 215ms	remaining: 5.16s
20:	learn: 10396.1032248	total: 224ms	remaining: 5.1s
21:	learn: 10338.0752278	total: 232ms	remaining: 5.04s
22:	learn: 10286.3756881	total: 245ms	remaining: 5.08s
23:	learn: 10233.3086308	total: 254ms	remaining: 5.04s
24:	learn: 10184.7901665	total: 262ms	remaining: 4.99s
25:	learn: 10139.3894255	total: 272ms	remaining: 4.96s
26:	learn: 10098.0100082	total: 281ms	remaining: 4.92s
27:	learn: 10058.2057845	total: 291ms	remaining: 4.9s
28:	learn: 10020.0066117	total: 300ms	remaining: 4.88s
29:	learn: 9984.9953372	total: 309ms	remaining: 4.84s
30:	learn: 9942.1078259	total: 322ms	remaining: 4.87s
31:	learn: 9901.3405030	total: 333ms	remaining: 4.87s
32:	learn: 9873.4657780	total: 343ms	remaining: 4.85s
33:	learn: 9845.3215544	total: 352ms	remaining: 4.82s
34:	learn: 9820.1888358	total: 361ms	remaining: 4.79s
35:	learn: 9794.2554651	total: 370ms	remaining: 4.76s
36:	learn: 9769.7856448	total: 378ms	remaining: 4.73s
37:	learn: 9748.5204927	total: 386ms	remaining: 4.69s
38:	learn: 9727.6726739	total: 394ms	remaining: 4.66s
39:	learn: 9706.5131135	total: 403ms	remaining: 4.64s
40:	learn: 9689.2747169	total: 412ms	remaining: 4.61s
41:	learn: 9668.8488023	total: 422ms	remaining: 4.6s
42:	learn: 9649.0151531	total: 430ms	remaining: 4.57s
43:	learn: 9631.6634217	total: 439ms	remaining: 4.54s
44:	learn: 9610.1880900	total: 447ms	remaining: 4.52s
45:	learn: 9594.8257275	total: 455ms	remaining: 4.49s
46:	learn: 9573.9798184	total: 464ms	remaining: 4.47s
47:	learn: 9558.5021692	total: 472ms	remaining: 4.45s
48:	learn: 9543.9087479	total: 483ms	remaining: 4.44s
49:	learn: 9530.3748622	total: 491ms	remaining: 4.42s
50:	learn: 9514.8461739	total: 499ms	remaining: 4.39s
51:	learn: 9502.8804121	total: 508ms	remaining: 4.37s
52:	learn: 9491.4427709	total: 516ms	remaining: 4.36s
53:	learn: 9480.2154362	total: 525ms	remaining: 4.33s
54:	learn: 9470.7002478	total: 533ms	remaining: 4.31s
55:	learn: 9458.5848733	total: 541ms	remaining: 4.29s
56:	learn: 9445.8399152	total: 549ms	remaining: 4.27s
57:	learn: 9423.4976294	total: 558ms	remaining: 4.25s
58:	learn: 9409.8236241	total: 566ms	remaining: 4.23s
59:	learn: 9398.8109988	total: 574ms	remaining: 4.21s
60:	learn: 9388.8676253	total: 583ms	remaining: 4.19s
61:	learn: 9378.9797981	total: 591ms	remaining: 4.18s
62:	learn: 9368.7710706	total: 599ms	remaining: 4.16s
63:	learn: 9354.5961614	total: 608ms	remaining: 4.14s
64:	learn: 9343.2049584	total: 617ms	remaining: 4.13s
65:	learn: 9332.9267448	total: 626ms	remaining: 4.11s
66:	learn: 9324.3702254	total: 635ms	remaining: 4.1s
67:	learn: 9315.2674455	total: 643ms	remaining: 4.08s
68:	learn: 9307.8896094	total: 652ms	remaining: 4.07s
69:	learn: 9298.2462688	total: 661ms	remaining: 4.06s
70:	learn: 9287.5898964	total: 670ms	remaining: 4.05s
71:	learn: 9275.3256097	total: 679ms	remaining: 4.03s
72:	learn: 9269.0972036	total: 687ms	remaining: 4.02s
73:	learn: 9263.1563077	total: 696ms	remaining: 4s
74:	learn: 9254.8793902	total: 705ms	remaining: 4s
75:	learn: 9242.1098222	total: 714ms	remaining: 3.98s
76:	learn: 9236.5180216	total: 722ms	remaining: 3.97s
77:	learn: 9228.5973901	total: 730ms	remaining: 3.95s
78:	learn: 9218.5287053	total: 739ms	remaining: 3.94s
79:	learn: 9213.8367647	total: 747ms	remaining: 3.92s
80:	learn: 9208.4719958	total: 756ms	remaining: 3.91s
81:	learn: 9195.5900301	total: 764ms	remaining: 3.9s
82:	learn: 9186.5112891	total: 773ms	remaining: 3.88s
83:	learn: 9178.0438860	total: 781ms	remaining: 3.87s
84:	learn: 9170.4504147	total: 790ms	remaining: 3.85s
85:	learn: 9162.8762055	total: 798ms	remaining: 3.84s
86:	learn: 9155.9754091	total: 807ms	remaining: 3.83s
87:	learn: 9148.7072405	total: 815ms	remaining: 3.82s
88:	learn: 9137.8786950	total: 824ms	remaining: 3.8s
89:	learn: 9132.3548267	total: 833ms	remaining: 3.79s
90:	learn: 9120.6723065	total: 841ms	remaining: 3.78s
91:	learn: 9111.3984008	total: 850ms	remaining: 3.77s
92:	learn: 9099.2421608	total: 858ms	remaining: 3.76s
93:	learn: 9095.1183252	total: 867ms	remaining: 3.75s
94:	learn: 9087.7759480	total: 876ms	remaining: 3.73s
95:	learn: 9082.8270491	total: 884ms	remaining: 3.72s
96:	learn: 9077.7575607	total: 894ms	remaining: 3.71s
97:	learn: 9072.9946707	total: 902ms	remaining: 3.7s
98:	learn: 9063.6180609	total: 910ms	remaining: 3.69s
99:	learn: 9057.0344658	total: 919ms	remaining: 3.67s
100:	learn: 9047.3837602	total: 927ms	remaining: 3.66s
101:	learn: 9042.1864071	total: 935ms	remaining: 3.65s
102:	learn: 9028.4103238	total: 944ms	remaining: 3.64s
103:	learn: 9018.0197885	total: 952ms	remaining: 3.63s
104:	learn: 9014.7239771	total: 961ms	remaining: 3.61s
105:	learn: 9004.9514651	total: 969ms	remaining: 3.6s
106:	learn: 9001.1129690	total: 978ms	remaining: 3.59s
107:	learn: 8987.4944764	total: 986ms	remaining: 3.58s
108:	learn: 8979.5512318	total: 995ms	remaining: 3.57s
109:	learn: 8974.5701461	total: 1s	remaining: 3.56s
110:	learn: 8968.2891535	total: 1.01s	remaining: 3.55s
111:	learn: 8959.9960594	total: 1.02s	remaining: 3.54s
112:	learn: 8951.3459218	total: 1.03s	remaining: 3.53s
113:	learn: 8943.4520827	total: 1.04s	remaining: 3.52s
114:	learn: 8935.6666632	total: 1.05s	remaining: 3.51s
115:	learn: 8932.2484204	total: 1.06s	remaining: 3.5s
116:	learn: 8920.8515730	total: 1.07s	remaining: 3.49s
117:	learn: 8911.0277303	total: 1.07s	remaining: 3.48s
118:	learn: 8903.9451756	total: 1.08s	remaining: 3.47s
119:	learn: 8895.4269859	total: 1.09s	remaining: 3.46s
120:	learn: 8879.8796421	total: 1.1s	remaining: 3.45s
121:	learn: 8868.4958474	total: 1.11s	remaining: 3.44s
122:	learn: 8856.6018442	total: 1.12s	remaining: 3.43s
123:	learn: 8853.4075353	total: 1.13s	remaining: 3.42s
124:	learn: 8842.7530566	total: 1.14s	remaining: 3.4s
125:	learn: 8838.0678490	total: 1.14s	remaining: 3.4s
126:	learn: 8831.5237496	total: 1.15s	remaining: 3.38s
127:	learn: 8824.7421783	total: 1.16s	remaining: 3.37s
128:	learn: 8811.8909259	total: 1.17s	remaining: 3.36s
129:	learn: 8804.7455703	total: 1.18s	remaining: 3.35s
130:	learn: 8797.2435414	total: 1.19s	remaining: 3.34s
131:	learn: 8783.3096179	total: 1.2s	remaining: 3.33s
132:	learn: 8772.2924100	total: 1.2s	remaining: 3.32s
133:	learn: 8765.8094200	total: 1.21s	remaining: 3.31s
134:	learn: 8761.8131809	total: 1.22s	remaining: 3.3s
135:	learn: 8751.1778694	total: 1.23s	remaining: 3.29s
136:	learn: 8743.8217086	total: 1.24s	remaining: 3.29s
137:	learn: 8737.8510122	total: 1.25s	remaining: 3.28s
138:	learn: 8730.9579788	total: 1.26s	remaining: 3.27s
139:	learn: 8723.1135363	total: 1.27s	remaining: 3.26s
140:	learn: 8714.0474509	total: 1.28s	remaining: 3.25s
141:	learn: 8706.5257203	total: 1.29s	remaining: 3.24s
142:	learn: 8700.4721112	total: 1.29s	remaining: 3.23s
143:	learn: 8695.3885661	total: 1.3s	remaining: 3.22s
144:	learn: 8691.2956529	total: 1.31s	remaining: 3.21s
145:	learn: 8683.1073859	total: 1.32s	remaining: 3.2s
146:	learn: 8678.2892742	total: 1.33s	remaining: 3.19s
147:	learn: 8675.8467568	total: 1.34s	remaining: 3.18s
148:	learn: 8669.9867983	total: 1.35s	remaining: 3.17s
149:	learn: 8664.4683508	total: 1.35s	remaining: 3.16s
150:	learn: 8651.9811858	total: 1.36s	remaining: 3.15s
151:	learn: 8644.8617273	total: 1.37s	remaining: 3.14s
152:	learn: 8640.7075018	total: 1.38s	remaining: 3.13s
153:	learn: 8632.1973618	total: 1.39s	remaining: 3.12s
154:	learn: 8622.0285550	total: 1.4s	remaining: 3.11s
155:	learn: 8616.0255074	total: 1.41s	remaining: 3.1s
156:	learn: 8604.7506800	total: 1.42s	remaining: 3.09s
157:	learn: 8597.5162889	total: 1.42s	remaining: 3.08s
158:	learn: 8586.9396456	total: 1.44s	remaining: 3.08s
159:	learn: 8579.9631500	total: 1.44s	remaining: 3.07s
160:	learn: 8577.7270923	total: 1.45s	remaining: 3.06s
161:	learn: 8570.0789532	total: 1.46s	remaining: 3.05s
162:	learn: 8559.3366120	total: 1.47s	remaining: 3.04s
163:	learn: 8551.3509942	total: 1.48s	remaining: 3.03s
164:	learn: 8543.1087365	total: 1.49s	remaining: 3.02s
165:	learn: 8538.7143407	total: 1.5s	remaining: 3.01s
166:	learn: 8527.7337741	total: 1.5s	remaining: 3s
167:	learn: 8521.9714475	total: 1.51s	remaining: 2.99s
168:	learn: 8513.8206205	total: 1.52s	remaining: 2.98s
169:	learn: 8504.4097672	total: 1.53s	remaining: 2.97s
170:	learn: 8493.8143649	total: 1.54s	remaining: 2.96s
171:	learn: 8489.6717556	total: 1.55s	remaining: 2.95s
172:	learn: 8478.3926200	total: 1.56s	remaining: 2.94s
173:	learn: 8468.1311816	total: 1.57s	remaining: 2.93s
174:	learn: 8462.5642470	total: 1.57s	remaining: 2.92s
175:	learn: 8451.0362121	total: 1.58s	remaining: 2.92s
176:	learn: 8447.3486395	total: 1.59s	remaining: 2.91s
177:	learn: 8442.8118559	total: 1.6s	remaining: 2.9s
178:	learn: 8436.3724363	total: 1.61s	remaining: 2.89s
179:	learn: 8430.3705493	total: 1.62s	remaining: 2.88s
180:	learn: 8426.6250380	total: 1.63s	remaining: 2.87s
181:	learn: 8421.2760135	total: 1.64s	remaining: 2.86s
182:	learn: 8418.4624620	total: 1.64s	remaining: 2.85s
183:	learn: 8411.4054997	total: 1.65s	remaining: 2.84s
184:	learn: 8406.2452325	total: 1.66s	remaining: 2.83s
185:	learn: 8398.0387730	total: 1.67s	remaining: 2.82s
186:	learn: 8391.4407713	total: 1.68s	remaining: 2.81s
187:	learn: 8387.3297065	total: 1.69s	remaining: 2.8s
188:	learn: 8380.8317021	total: 1.7s	remaining: 2.79s
189:	learn: 8376.5487404	total: 1.71s	remaining: 2.78s
190:	learn: 8368.9086152	total: 1.71s	remaining: 2.77s
191:	learn: 8361.7607917	total: 1.72s	remaining: 2.76s
192:	learn: 8353.7850865	total: 1.73s	remaining: 2.75s
193:	learn: 8349.6807582	total: 1.74s	remaining: 2.75s
194:	learn: 8339.9227061	total: 1.75s	remaining: 2.74s
195:	learn: 8334.2846518	total: 1.76s	remaining: 2.73s
196:	learn: 8327.2184691	total: 1.77s	remaining: 2.72s
197:	learn: 8319.9565827	total: 1.77s	remaining: 2.71s
198:	learn: 8313.4896949	total: 1.78s	remaining: 2.7s
199:	learn: 8306.9702912	total: 1.79s	remaining: 2.69s
200:	learn: 8302.1651179	total: 1.8s	remaining: 2.68s
201:	learn: 8297.1303951	total: 1.81s	remaining: 2.67s
202:	learn: 8291.4590449	total: 1.82s	remaining: 2.66s
203:	learn: 8282.2727221	total: 1.83s	remaining: 2.65s
204:	learn: 8273.4010471	total: 1.83s	remaining: 2.64s
205:	learn: 8264.6105904	total: 1.84s	remaining: 2.63s
206:	learn: 8257.8357679	total: 1.85s	remaining: 2.62s
207:	learn: 8252.8025992	total: 1.86s	remaining: 2.61s
208:	learn: 8249.5271861	total: 1.87s	remaining: 2.6s
209:	learn: 8242.2636248	total: 1.88s	remaining: 2.59s
210:	learn: 8233.0223968	total: 1.89s	remaining: 2.58s
211:	learn: 8226.5025922	total: 1.9s	remaining: 2.58s
212:	learn: 8221.5317510	total: 1.91s	remaining: 2.57s
213:	learn: 8216.9836353	total: 1.91s	remaining: 2.56s
214:	learn: 8212.3270418	total: 1.92s	remaining: 2.55s
215:	learn: 8205.0064703	total: 1.93s	remaining: 2.54s
216:	learn: 8200.0033724	total: 1.94s	remaining: 2.53s
217:	learn: 8193.5940258	total: 1.95s	remaining: 2.52s
218:	learn: 8186.8189872	total: 1.96s	remaining: 2.51s
219:	learn: 8181.1908403	total: 1.97s	remaining: 2.5s
220:	learn: 8175.7316695	total: 1.97s	remaining: 2.49s
221:	learn: 8169.9302858	total: 1.98s	remaining: 2.48s
222:	learn: 8161.1695993	total: 1.99s	remaining: 2.47s
223:	learn: 8156.4808655	total: 2s	remaining: 2.46s
224:	learn: 8150.4853696	total: 2.01s	remaining: 2.45s
225:	learn: 8144.7303937	total: 2.02s	remaining: 2.44s
226:	learn: 8140.2386663	total: 2.02s	remaining: 2.44s
227:	learn: 8131.2083056	total: 2.03s	remaining: 2.43s
228:	learn: 8126.4805410	total: 2.04s	remaining: 2.42s
229:	learn: 8122.4420665	total: 2.05s	remaining: 2.41s
230:	learn: 8115.3153078	total: 2.06s	remaining: 2.4s
231:	learn: 8112.8226542	total: 2.07s	remaining: 2.39s
232:	learn: 8109.2467438	total: 2.08s	remaining: 2.38s
233:	learn: 8103.3193178	total: 2.08s	remaining: 2.37s
234:	learn: 8095.8720511	total: 2.09s	remaining: 2.36s
235:	learn: 8088.7879141	total: 2.1s	remaining: 2.35s
236:	learn: 8086.0376073	total: 2.11s	remaining: 2.34s
237:	learn: 8079.0719063	total: 2.12s	remaining: 2.33s
238:	learn: 8073.9401908	total: 2.13s	remaining: 2.32s
239:	learn: 8068.1661904	total: 2.14s	remaining: 2.31s
240:	learn: 8060.8418096	total: 2.15s	remaining: 2.31s
241:	learn: 8055.5727290	total: 2.15s	remaining: 2.3s
242:	learn: 8050.6509351	total: 2.16s	remaining: 2.29s
243:	learn: 8041.7655214	total: 2.17s	remaining: 2.28s
244:	learn: 8034.9118761	total: 2.18s	remaining: 2.27s
245:	learn: 8026.4486211	total: 2.19s	remaining: 2.26s
246:	learn: 8021.2651862	total: 2.2s	remaining: 2.25s
247:	learn: 8016.7125082	total: 2.2s	remaining: 2.24s
248:	learn: 8013.0143392	total: 2.21s	remaining: 2.23s
249:	learn: 8006.6587780	total: 2.22s	remaining: 2.22s
250:	learn: 7999.4986109	total: 2.23s	remaining: 2.21s
251:	learn: 7995.8720423	total: 2.24s	remaining: 2.2s
252:	learn: 7992.0762238	total: 2.25s	remaining: 2.19s
253:	learn: 7984.1325660	total: 2.25s	remaining: 2.18s
254:	learn: 7975.7921534	total: 2.26s	remaining: 2.17s
255:	learn: 7966.4698540	total: 2.27s	remaining: 2.17s
256:	learn: 7955.8710514	total: 2.28s	remaining: 2.16s
257:	learn: 7951.2994261	total: 2.29s	remaining: 2.15s
258:	learn: 7945.5489831	total: 2.3s	remaining: 2.14s
259:	learn: 7937.6370050	total: 2.31s	remaining: 2.13s
260:	learn: 7928.5977968	total: 2.32s	remaining: 2.12s
261:	learn: 7924.8538481	total: 2.33s	remaining: 2.11s
262:	learn: 7922.8433089	total: 2.33s	remaining: 2.1s
263:	learn: 7916.2206106	total: 2.34s	remaining: 2.1s
264:	learn: 7909.7796901	total: 2.35s	remaining: 2.08s
265:	learn: 7906.2272536	total: 2.36s	remaining: 2.08s
266:	learn: 7894.1767775	total: 2.37s	remaining: 2.07s
267:	learn: 7885.9547826	total: 2.38s	remaining: 2.06s
268:	learn: 7883.2409375	total: 2.39s	remaining: 2.05s
269:	learn: 7876.5379057	total: 2.4s	remaining: 2.04s
270:	learn: 7871.6403001	total: 2.4s	remaining: 2.03s
271:	learn: 7868.7602599	total: 2.41s	remaining: 2.02s
272:	learn: 7862.1200899	total: 2.42s	remaining: 2.01s
273:	learn: 7854.5737862	total: 2.43s	remaining: 2s
274:	learn: 7848.2609657	total: 2.44s	remaining: 1.99s
275:	learn: 7841.5171451	total: 2.45s	remaining: 1.99s
276:	learn: 7836.2195307	total: 2.45s	remaining: 1.98s
277:	learn: 7829.6033484	total: 2.46s	remaining: 1.97s
278:	learn: 7821.4301049	total: 2.47s	remaining: 1.96s
279:	learn: 7815.3256754	total: 2.48s	remaining: 1.95s
280:	learn: 7811.1903526	total: 2.49s	remaining: 1.94s
281:	learn: 7806.2389837	total: 2.5s	remaining: 1.93s
282:	learn: 7799.5848337	total: 2.5s	remaining: 1.92s
283:	learn: 7791.0234529	total: 2.51s	remaining: 1.91s
284:	learn: 7781.8301056	total: 2.52s	remaining: 1.9s
285:	learn: 7775.9522632	total: 2.53s	remaining: 1.89s
286:	learn: 7771.9190239	total: 2.54s	remaining: 1.88s
287:	learn: 7760.5251564	total: 2.55s	remaining: 1.88s
288:	learn: 7753.7174564	total: 2.56s	remaining: 1.87s
289:	learn: 7750.2448202	total: 2.56s	remaining: 1.86s
290:	learn: 7748.7055902	total: 2.57s	remaining: 1.85s
291:	learn: 7741.3689626	total: 2.58s	remaining: 1.84s
292:	learn: 7733.3487007	total: 2.59s	remaining: 1.83s
293:	learn: 7725.7211145	total: 2.6s	remaining: 1.82s
294:	learn: 7719.7121144	total: 2.61s	remaining: 1.81s
295:	learn: 7714.6341057	total: 2.61s	remaining: 1.8s
296:	learn: 7707.4990063	total: 2.62s	remaining: 1.79s
297:	learn: 7704.8971286	total: 2.63s	remaining: 1.78s
298:	learn: 7699.2516298	total: 2.64s	remaining: 1.77s
299:	learn: 7694.2527165	total: 2.65s	remaining: 1.76s
300:	learn: 7689.2769552	total: 2.66s	remaining: 1.76s
301:	learn: 7683.2664373	total: 2.67s	remaining: 1.75s
302:	learn: 7681.2455478	total: 2.67s	remaining: 1.74s
303:	learn: 7676.3434314	total: 2.68s	remaining: 1.73s
304:	learn: 7666.3923762	total: 2.69s	remaining: 1.72s
305:	learn: 7660.1925491	total: 2.7s	remaining: 1.71s
306:	learn: 7654.9040791	total: 2.71s	remaining: 1.7s
307:	learn: 7648.7940826	total: 2.72s	remaining: 1.69s
308:	learn: 7641.0526432	total: 2.72s	remaining: 1.68s
309:	learn: 7633.6898866	total: 2.73s	remaining: 1.68s
310:	learn: 7625.0627626	total: 2.74s	remaining: 1.67s
311:	learn: 7622.5155504	total: 2.75s	remaining: 1.66s
312:	learn: 7616.7678719	total: 2.76s	remaining: 1.65s
313:	learn: 7611.6189942	total: 2.77s	remaining: 1.64s
314:	learn: 7604.3240625	total: 2.77s	remaining: 1.63s
315:	learn: 7598.6912679	total: 2.78s	remaining: 1.62s
316:	learn: 7593.6740841	total: 2.79s	remaining: 1.61s
317:	learn: 7588.2055067	total: 2.8s	remaining: 1.6s
318:	learn: 7581.6409062	total: 2.81s	remaining: 1.59s
319:	learn: 7577.2236096	total: 2.82s	remaining: 1.58s
320:	learn: 7572.5144797	total: 2.83s	remaining: 1.58s
321:	learn: 7568.1923202	total: 2.83s	remaining: 1.57s
322:	learn: 7560.3680530	total: 2.84s	remaining: 1.56s
323:	learn: 7556.1513736	total: 2.85s	remaining: 1.55s
324:	learn: 7553.1133482	total: 2.86s	remaining: 1.54s
325:	learn: 7547.7413237	total: 2.87s	remaining: 1.53s
326:	learn: 7541.5273261	total: 2.88s	remaining: 1.52s
327:	learn: 7536.7136087	total: 2.89s	remaining: 1.51s
328:	learn: 7531.4184677	total: 2.9s	remaining: 1.5s
329:	learn: 7524.1949461	total: 2.9s	remaining: 1.5s
330:	learn: 7521.1993023	total: 2.91s	remaining: 1.49s
331:	learn: 7515.7451069	total: 2.92s	remaining: 1.48s
332:	learn: 7508.5630693	total: 2.93s	remaining: 1.47s
333:	learn: 7504.7129165	total: 2.94s	remaining: 1.46s
334:	learn: 7501.0468060	total: 2.95s	remaining: 1.45s
335:	learn: 7499.6332657	total: 2.96s	remaining: 1.44s
336:	learn: 7493.7195273	total: 2.96s	remaining: 1.43s
337:	learn: 7489.5047726	total: 2.97s	remaining: 1.42s
338:	learn: 7485.5347715	total: 2.98s	remaining: 1.42s
339:	learn: 7480.4577844	total: 2.99s	remaining: 1.41s
340:	learn: 7472.2789087	total: 3s	remaining: 1.4s
341:	learn: 7466.7706838	total: 3.01s	remaining: 1.39s
342:	learn: 7462.5414774	total: 3.02s	remaining: 1.38s
343:	learn: 7456.2904214	total: 3.02s	remaining: 1.37s
344:	learn: 7450.7170497	total: 3.03s	remaining: 1.36s
345:	learn: 7447.6135142	total: 3.04s	remaining: 1.35s
346:	learn: 7441.3006550	total: 3.05s	remaining: 1.34s
347:	learn: 7436.3744502	total: 3.06s	remaining: 1.34s
348:	learn: 7433.0863511	total: 3.07s	remaining: 1.33s
349:	learn: 7429.7766083	total: 3.08s	remaining: 1.32s
350:	learn: 7423.9710404	total: 3.08s	remaining: 1.31s
351:	learn: 7418.9965737	total: 3.09s	remaining: 1.3s
352:	learn: 7408.0069574	total: 3.1s	remaining: 1.29s
353:	learn: 7403.6634068	total: 3.11s	remaining: 1.28s
354:	learn: 7400.0390681	total: 3.12s	remaining: 1.27s
355:	learn: 7398.2438588	total: 3.13s	remaining: 1.26s
356:	learn: 7393.6034624	total: 3.14s	remaining: 1.26s
357:	learn: 7387.7902962	total: 3.15s	remaining: 1.25s
358:	learn: 7381.1674993	total: 3.15s	remaining: 1.24s
359:	learn: 7375.0113298	total: 3.16s	remaining: 1.23s
360:	learn: 7370.8601941	total: 3.17s	remaining: 1.22s
361:	learn: 7367.9390634	total: 3.18s	remaining: 1.21s
362:	learn: 7366.1421936	total: 3.19s	remaining: 1.2s
363:	learn: 7362.2981524	total: 3.2s	remaining: 1.19s
364:	learn: 7354.1040002	total: 3.21s	remaining: 1.19s
365:	learn: 7349.9313668	total: 3.21s	remaining: 1.18s

In [15]:
metrics_traffic = pd.concat([ridge_metrics_traffic, knn_metrics_traffic, rf_metrics_traffic, catboost_metrics_traffic, mlp_metrics_traffic], axis=0)
metrics_traffic

  Целевая переменная           Модель          RMSE          MAE
0             Трафик  RidgeRegression  10093.962408  7647.526369
0             Трафик              KNN   6785.831310  3856.275327
0             Трафик     RandomForest   3843.241801  2280.605389
0             Трафик         CATBOOST   7275.962785  5424.699857
0             Трафик              MLP   5605.070000  4021.380000

In [25]:
fig = px.bar(
    metrics_traffic.sort_values(['RMSE', 'MAE']),
    x='Модель',
    y=['RMSE', 'MAE'],
    barmode='group',
    title='Результаты функционала ошибок для предсказания трафика'
)

fig.show()

## Средний чек

In [16]:
rf_best_params_average_bill = {
    'n_estimators': [1000],
    'max_depth': [50],
    'max_features': [0.63],
    'max_samples': [1.0]
}

In [17]:
mlp_metrics_average_bill = pd.DataFrame({
    'Целевая переменная' : ['Средний чек'],
    'Модель' : ['MLP'],
    'RMSE' : [121.62],
    'MAE' : [89.13]
})
mlp_metrics_average_bill

  Целевая переменная Модель    RMSE    MAE
0        Средний чек    MLP  121.62  89.13

In [18]:
ridge_metrics_average_bill = metrics_compare(
    Ridge(alpha=1.0),
    'RidgeRegression',
    'Средний чек'
)

knn_metrics_average_bill = metrics_compare(
    KNeighborsRegressor(n_neighbors=1, n_jobs=-1),
    'KNN',
    'Средний чек'
)

rf_metrics_average_bill = metrics_compare(
    RandomForestRegressor(
        max_depth=50,
        max_features=0.63,
        max_samples=1.0,
        n_estimators=1000,
        random_state=598
    ),
    'RandomForest',
    'Средний чек'
)

catboost_metrics_average_bill = metrics_compare(
    CatBoostRegressor(learning_rate=0.05, l2_leaf_reg=1, iterations=500, depth=10, random_state=1337),
    'CATBOOST',
    'Средний чек'
)

0:	learn: 305.6671470	total: 24.7ms	remaining: 12.3s
1:	learn: 297.9752173	total: 39.9ms	remaining: 9.93s
2:	learn: 290.7986506	total: 48.8ms	remaining: 8.09s
3:	learn: 284.0972895	total: 57.4ms	remaining: 7.12s
4:	learn: 277.9422236	total: 66.1ms	remaining: 6.54s
5:	learn: 272.1493150	total: 74.7ms	remaining: 6.15s
6:	learn: 266.8633939	total: 83.1ms	remaining: 5.85s
7:	learn: 261.8478661	total: 91.3ms	remaining: 5.62s
8:	learn: 257.2179963	total: 100ms	remaining: 5.45s
9:	learn: 252.9871890	total: 108ms	remaining: 5.3s
10:	learn: 249.0682215	total: 118ms	remaining: 5.25s
11:	learn: 245.4204684	total: 126ms	remaining: 5.14s
12:	learn: 242.0732158	total: 135ms	remaining: 5.04s
13:	learn: 238.9519388	total: 143ms	remaining: 4.97s
14:	learn: 236.1056771	total: 153ms	remaining: 4.94s
15:	learn: 233.4759463	total: 161ms	remaining: 4.88s
16:	learn: 231.0035490	total: 170ms	remaining: 4.83s
17:	learn: 228.7500926	total: 179ms	remaining: 4.79s
18:	learn: 226.6148657	total: 187ms	remaining: 4.74s
19:	learn: 224.6427358	total: 196ms	remaining: 4.7s
20:	learn: 222.8021449	total: 204ms	remaining: 4.66s
21:	learn: 221.0663321	total: 213ms	remaining: 4.63s
22:	learn: 219.4577284	total: 222ms	remaining: 4.61s
23:	learn: 217.9979741	total: 232ms	remaining: 4.6s
24:	learn: 216.6069817	total: 241ms	remaining: 4.57s
25:	learn: 215.2521098	total: 251ms	remaining: 4.57s
26:	learn: 214.0647968	total: 265ms	remaining: 4.63s
27:	learn: 213.0189552	total: 275ms	remaining: 4.63s
28:	learn: 212.0351839	total: 301ms	remaining: 4.88s
29:	learn: 210.9797228	total: 321ms	remaining: 5.04s
30:	learn: 209.9850071	total: 332ms	remaining: 5.02s
31:	learn: 209.0188074	total: 342ms	remaining: 5s
32:	learn: 208.1679822	total: 351ms	remaining: 4.97s
33:	learn: 207.2954368	total: 360ms	remaining: 4.93s
34:	learn: 206.5322465	total: 369ms	remaining: 4.9s
35:	learn: 205.8610554	total: 378ms	remaining: 4.87s
36:	learn: 205.1160699	total: 387ms	remaining: 4.84s
37:	learn: 204.4237280	total: 396ms	remaining: 4.81s
38:	learn: 203.7241259	total: 404ms	remaining: 4.78s
39:	learn: 203.1296686	total: 414ms	remaining: 4.76s
40:	learn: 202.4733049	total: 424ms	remaining: 4.75s
41:	learn: 201.8877152	total: 432ms	remaining: 4.72s
42:	learn: 201.3728085	total: 441ms	remaining: 4.69s
43:	learn: 200.6898567	total: 450ms	remaining: 4.66s
44:	learn: 200.1627386	total: 459ms	remaining: 4.64s
45:	learn: 199.7092921	total: 468ms	remaining: 4.62s
46:	learn: 199.2211866	total: 478ms	remaining: 4.6s
47:	learn: 198.7859083	total: 487ms	remaining: 4.59s
48:	learn: 198.4341784	total: 496ms	remaining: 4.57s
49:	learn: 197.9831767	total: 505ms	remaining: 4.55s
50:	learn: 197.6209969	total: 514ms	remaining: 4.53s
51:	learn: 197.1482128	total: 523ms	remaining: 4.5s
52:	learn: 196.7709328	total: 532ms	remaining: 4.49s
53:	learn: 196.4440828	total: 540ms	remaining: 4.46s
54:	learn: 196.0470561	total: 549ms	remaining: 4.44s
55:	learn: 195.6029297	total: 557ms	remaining: 4.42s
56:	learn: 195.1563362	total: 567ms	remaining: 4.4s
57:	learn: 194.7674830	total: 576ms	remaining: 4.39s
58:	learn: 194.3714823	total: 584ms	remaining: 4.37s
59:	learn: 194.0998157	total: 593ms	remaining: 4.35s
60:	learn: 193.7458166	total: 602ms	remaining: 4.33s
61:	learn: 193.5247563	total: 610ms	remaining: 4.31s
62:	learn: 193.1860890	total: 619ms	remaining: 4.29s
63:	learn: 192.8166632	total: 627ms	remaining: 4.27s
64:	learn: 192.5414193	total: 636ms	remaining: 4.26s
65:	learn: 192.1479354	total: 645ms	remaining: 4.24s
66:	learn: 191.9022094	total: 654ms	remaining: 4.22s
67:	learn: 191.6227178	total: 662ms	remaining: 4.21s
68:	learn: 191.3337665	total: 671ms	remaining: 4.19s
69:	learn: 191.0205023	total: 680ms	remaining: 4.18s
70:	learn: 190.8197249	total: 689ms	remaining: 4.16s
71:	learn: 190.6165494	total: 697ms	remaining: 4.14s
72:	learn: 190.3498485	total: 706ms	remaining: 4.13s
73:	learn: 190.0930732	total: 715ms	remaining: 4.11s
74:	learn: 189.8905122	total: 724ms	remaining: 4.1s
75:	learn: 189.6650535	total: 733ms	remaining: 4.09s
76:	learn: 189.4633783	total: 741ms	remaining: 4.07s
77:	learn: 189.2624738	total: 750ms	remaining: 4.06s
78:	learn: 189.0902313	total: 759ms	remaining: 4.04s
79:	learn: 188.8613775	total: 768ms	remaining: 4.03s
80:	learn: 188.4893273	total: 776ms	remaining: 4.01s
81:	learn: 188.3489640	total: 785ms	remaining: 4s
82:	learn: 188.1120785	total: 793ms	remaining: 3.98s
83:	learn: 187.8648583	total: 802ms	remaining: 3.97s
84:	learn: 187.5723774	total: 810ms	remaining: 3.96s
85:	learn: 187.3169420	total: 819ms	remaining: 3.94s
86:	learn: 187.1458268	total: 828ms	remaining: 3.93s
87:	learn: 186.9822057	total: 837ms	remaining: 3.92s
88:	learn: 186.6889336	total: 846ms	remaining: 3.91s
89:	learn: 186.5039894	total: 855ms	remaining: 3.9s
90:	learn: 186.2378970	total: 864ms	remaining: 3.88s
91:	learn: 185.9221190	total: 873ms	remaining: 3.87s
92:	learn: 185.7983136	total: 882ms	remaining: 3.86s
93:	learn: 185.5873248	total: 891ms	remaining: 3.85s
94:	learn: 185.3885893	total: 900ms	remaining: 3.84s
95:	learn: 185.2852650	total: 908ms	remaining: 3.82s
96:	learn: 185.1096876	total: 917ms	remaining: 3.81s
97:	learn: 184.9532244	total: 926ms	remaining: 3.8s
98:	learn: 184.7920417	total: 935ms	remaining: 3.79s
99:	learn: 184.5371485	total: 944ms	remaining: 3.78s
100:	learn: 184.2647737	total: 953ms	remaining: 3.76s
101:	learn: 184.0663109	total: 961ms	remaining: 3.75s
102:	learn: 183.9076634	total: 970ms	remaining: 3.74s
103:	learn: 183.7023077	total: 979ms	remaining: 3.73s
104:	learn: 183.5519289	total: 988ms	remaining: 3.72s
105:	learn: 183.2856506	total: 997ms	remaining: 3.71s
106:	learn: 183.0573256	total: 1s	remaining: 3.69s
107:	learn: 182.8551777	total: 1.01s	remaining: 3.68s
108:	learn: 182.6655892	total: 1.02s	remaining: 3.67s
109:	learn: 182.5582640	total: 1.03s	remaining: 3.65s
110:	learn: 182.4562314	total: 1.04s	remaining: 3.64s
111:	learn: 182.3460028	total: 1.05s	remaining: 3.63s
112:	learn: 182.1626965	total: 1.06s	remaining: 3.62s
113:	learn: 182.0078499	total: 1.07s	remaining: 3.61s
114:	learn: 181.8569861	total: 1.07s	remaining: 3.6s
115:	learn: 181.5917884	total: 1.08s	remaining: 3.59s
116:	learn: 181.4004813	total: 1.09s	remaining: 3.58s
117:	learn: 181.2799972	total: 1.1s	remaining: 3.57s
118:	learn: 181.1567063	total: 1.11s	remaining: 3.56s
119:	learn: 181.0639833	total: 1.12s	remaining: 3.55s
120:	learn: 180.9129224	total: 1.13s	remaining: 3.54s
121:	learn: 180.7067444	total: 1.14s	remaining: 3.53s
122:	learn: 180.4477172	total: 1.15s	remaining: 3.52s
123:	learn: 180.3328342	total: 1.16s	remaining: 3.51s
124:	learn: 180.0761397	total: 1.17s	remaining: 3.5s
125:	learn: 179.9532463	total: 1.17s	remaining: 3.49s
126:	learn: 179.8498467	total: 1.18s	remaining: 3.48s
127:	learn: 179.7298899	total: 1.19s	remaining: 3.46s
128:	learn: 179.4414227	total: 1.2s	remaining: 3.45s
129:	learn: 179.2982124	total: 1.21s	remaining: 3.44s
130:	learn: 179.0955551	total: 1.22s	remaining: 3.43s
131:	learn: 178.9741245	total: 1.23s	remaining: 3.42s
132:	learn: 178.8638929	total: 1.24s	remaining: 3.41s
133:	learn: 178.7777323	total: 1.24s	remaining: 3.4s
134:	learn: 178.6797266	total: 1.25s	remaining: 3.39s
135:	learn: 178.5876958	total: 1.26s	remaining: 3.38s
136:	learn: 178.3254405	total: 1.27s	remaining: 3.37s
137:	learn: 178.1729664	total: 1.28s	remaining: 3.36s
138:	learn: 178.0872323	total: 1.29s	remaining: 3.35s
139:	learn: 177.9117356	total: 1.3s	remaining: 3.34s
140:	learn: 177.7816861	total: 1.31s	remaining: 3.33s
141:	learn: 177.6804812	total: 1.31s	remaining: 3.31s
142:	learn: 177.5619495	total: 1.32s	remaining: 3.3s
143:	learn: 177.4846130	total: 1.33s	remaining: 3.29s
144:	learn: 177.3163456	total: 1.34s	remaining: 3.28s
145:	learn: 177.2027747	total: 1.35s	remaining: 3.27s
146:	learn: 177.0235934	total: 1.36s	remaining: 3.26s
147:	learn: 176.8820252	total: 1.37s	remaining: 3.25s
148:	learn: 176.7677028	total: 1.38s	remaining: 3.24s
149:	learn: 176.6212036	total: 1.38s	remaining: 3.23s
150:	learn: 176.4632750	total: 1.39s	remaining: 3.22s
151:	learn: 176.2446151	total: 1.4s	remaining: 3.21s
152:	learn: 176.0070893	total: 1.41s	remaining: 3.2s
153:	learn: 175.8729015	total: 1.42s	remaining: 3.19s
154:	learn: 175.7497215	total: 1.43s	remaining: 3.17s
155:	learn: 175.6841531	total: 1.44s	remaining: 3.17s
156:	learn: 175.5122158	total: 1.44s	remaining: 3.15s
157:	learn: 175.4064104	total: 1.45s	remaining: 3.14s
158:	learn: 175.3351792	total: 1.46s	remaining: 3.13s
159:	learn: 175.2239026	total: 1.47s	remaining: 3.12s
160:	learn: 174.9995276	total: 1.48s	remaining: 3.11s
161:	learn: 174.8616255	total: 1.49s	remaining: 3.1s
162:	learn: 174.6866129	total: 1.49s	remaining: 3.09s
163:	learn: 174.5849088	total: 1.5s	remaining: 3.08s
164:	learn: 174.5089971	total: 1.51s	remaining: 3.07s
165:	learn: 174.4387485	total: 1.52s	remaining: 3.06s
166:	learn: 174.2565427	total: 1.53s	remaining: 3.05s
167:	learn: 174.0522430	total: 1.54s	remaining: 3.04s
168:	learn: 173.9259539	total: 1.54s	remaining: 3.03s
169:	learn: 173.7449764	total: 1.55s	remaining: 3.02s
170:	learn: 173.4361108	total: 1.56s	remaining: 3.01s
171:	learn: 173.3424475	total: 1.57s	remaining: 3s
172:	learn: 173.2498076	total: 1.58s	remaining: 2.99s
173:	learn: 173.0595042	total: 1.59s	remaining: 2.98s
174:	learn: 172.9261148	total: 1.6s	remaining: 2.96s
175:	learn: 172.7230489	total: 1.6s	remaining: 2.95s
176:	learn: 172.6037532	total: 1.61s	remaining: 2.94s
177:	learn: 172.4540356	total: 1.62s	remaining: 2.93s
178:	learn: 172.3378414	total: 1.63s	remaining: 2.92s
179:	learn: 172.1943374	total: 1.64s	remaining: 2.91s
180:	learn: 172.1129607	total: 1.65s	remaining: 2.9s
181:	learn: 172.0141781	total: 1.65s	remaining: 2.89s
182:	learn: 171.8829512	total: 1.66s	remaining: 2.88s
183:	learn: 171.7430805	total: 1.67s	remaining: 2.87s
184:	learn: 171.6582641	total: 1.68s	remaining: 2.86s
185:	learn: 171.4581817	total: 1.69s	remaining: 2.85s
186:	learn: 171.3145994	total: 1.7s	remaining: 2.84s
187:	learn: 171.1765702	total: 1.71s	remaining: 2.83s
188:	learn: 171.0900234	total: 1.71s	remaining: 2.82s
189:	learn: 170.9719440	total: 1.72s	remaining: 2.81s
190:	learn: 170.7547060	total: 1.73s	remaining: 2.8s
191:	learn: 170.6400381	total: 1.74s	remaining: 2.79s
192:	learn: 170.4393364	total: 1.75s	remaining: 2.78s
193:	learn: 170.3775488	total: 1.76s	remaining: 2.77s
194:	learn: 170.2109217	total: 1.76s	remaining: 2.76s
195:	learn: 170.1494238	total: 1.77s	remaining: 2.75s
196:	learn: 170.0340658	total: 1.78s	remaining: 2.74s
197:	learn: 169.9811368	total: 1.79s	remaining: 2.73s
198:	learn: 169.8364553	total: 1.8s	remaining: 2.72s
199:	learn: 169.6681765	total: 1.81s	remaining: 2.71s
200:	learn: 169.4804876	total: 1.82s	remaining: 2.7s
201:	learn: 169.3188579	total: 1.82s	remaining: 2.69s
202:	learn: 169.2088054	total: 1.83s	remaining: 2.68s
203:	learn: 169.1382752	total: 1.84s	remaining: 2.67s
204:	learn: 169.0194833	total: 1.85s	remaining: 2.66s
205:	learn: 168.9165709	total: 1.86s	remaining: 2.65s
206:	learn: 168.8172043	total: 1.87s	remaining: 2.64s
207:	learn: 168.7158634	total: 1.88s	remaining: 2.63s
208:	learn: 168.6290908	total: 1.89s	remaining: 2.63s
209:	learn: 168.4944409	total: 1.89s	remaining: 2.62s
210:	learn: 168.2511262	total: 1.9s	remaining: 2.61s
211:	learn: 168.1436470	total: 1.91s	remaining: 2.6s
212:	learn: 168.0559502	total: 1.92s	remaining: 2.59s
213:	learn: 167.8631861	total: 1.93s	remaining: 2.58s
214:	learn: 167.7364491	total: 1.94s	remaining: 2.57s
215:	learn: 167.5217487	total: 1.95s	remaining: 2.56s
216:	learn: 167.4334026	total: 1.95s	remaining: 2.55s
217:	learn: 167.3747707	total: 1.96s	remaining: 2.54s
218:	learn: 167.1541121	total: 1.97s	remaining: 2.53s
219:	learn: 166.9940357	total: 1.98s	remaining: 2.52s
220:	learn: 166.9084788	total: 1.99s	remaining: 2.51s
221:	learn: 166.8334668	total: 2s	remaining: 2.5s
222:	learn: 166.6637350	total: 2s	remaining: 2.49s
223:	learn: 166.5750081	total: 2.01s	remaining: 2.48s
224:	learn: 166.5157730	total: 2.02s	remaining: 2.47s
225:	learn: 166.4174109	total: 2.03s	remaining: 2.46s
226:	learn: 166.2701308	total: 2.04s	remaining: 2.45s
227:	learn: 166.0954232	total: 2.05s	remaining: 2.44s
228:	learn: 165.9731039	total: 2.06s	remaining: 2.43s
229:	learn: 165.9087193	total: 2.06s	remaining: 2.42s
230:	learn: 165.8039343	total: 2.07s	remaining: 2.41s
231:	learn: 165.6457589	total: 2.08s	remaining: 2.4s
232:	learn: 165.5245020	total: 2.09s	remaining: 2.39s
233:	learn: 165.3680260	total: 2.1s	remaining: 2.38s
234:	learn: 165.2646528	total: 2.11s	remaining: 2.38s
235:	learn: 165.1008556	total: 2.12s	remaining: 2.37s
236:	learn: 164.9910372	total: 2.12s	remaining: 2.36s
237:	learn: 164.8148026	total: 2.13s	remaining: 2.35s
238:	learn: 164.7096616	total: 2.14s	remaining: 2.34s
239:	learn: 164.4684053	total: 2.15s	remaining: 2.33s
240:	learn: 164.3271745	total: 2.16s	remaining: 2.32s
241:	learn: 164.2085436	total: 2.17s	remaining: 2.31s
242:	learn: 163.9885068	total: 2.17s	remaining: 2.3s
243:	learn: 163.8828609	total: 2.18s	remaining: 2.29s
244:	learn: 163.7892877	total: 2.19s	remaining: 2.28s
245:	learn: 163.6809853	total: 2.2s	remaining: 2.27s
246:	learn: 163.5674377	total: 2.21s	remaining: 2.26s
247:	learn: 163.4974678	total: 2.22s	remaining: 2.25s
248:	learn: 163.3393640	total: 2.23s	remaining: 2.24s
249:	learn: 163.1672221	total: 2.23s	remaining: 2.23s
250:	learn: 163.0242350	total: 2.24s	remaining: 2.22s
251:	learn: 162.9117744	total: 2.25s	remaining: 2.21s
252:	learn: 162.7877823	total: 2.26s	remaining: 2.2s
253:	learn: 162.6620583	total: 2.27s	remaining: 2.19s
254:	learn: 162.5583729	total: 2.27s	remaining: 2.19s
255:	learn: 162.5074867	total: 2.28s	remaining: 2.18s
256:	learn: 162.2792863	total: 2.29s	remaining: 2.17s
257:	learn: 162.1209399	total: 2.3s	remaining: 2.16s
258:	learn: 162.0250455	total: 2.31s	remaining: 2.15s
259:	learn: 161.8485669	total: 2.32s	remaining: 2.14s
260:	learn: 161.7314981	total: 2.33s	remaining: 2.13s
261:	learn: 161.6673863	total: 2.33s	remaining: 2.12s
262:	learn: 161.5446172	total: 2.34s	remaining: 2.11s
263:	learn: 161.4384477	total: 2.35s	remaining: 2.1s
264:	learn: 161.2981124	total: 2.36s	remaining: 2.09s
265:	learn: 161.1742005	total: 2.37s	remaining: 2.08s
266:	learn: 161.0634053	total: 2.38s	remaining: 2.07s
267:	learn: 160.9692317	total: 2.38s	remaining: 2.06s
268:	learn: 160.9137086	total: 2.39s	remaining: 2.06s
269:	learn: 160.7266588	total: 2.4s	remaining: 2.05s
270:	learn: 160.6433019	total: 2.41s	remaining: 2.04s
271:	learn: 160.5561929	total: 2.42s	remaining: 2.03s
272:	learn: 160.3990959	total: 2.43s	remaining: 2.02s
273:	learn: 160.2442451	total: 2.44s	remaining: 2.01s
274:	learn: 160.0691575	total: 2.44s	remaining: 2s
275:	learn: 159.9329274	total: 2.45s	remaining: 1.99s
276:	learn: 159.7747628	total: 2.46s	remaining: 1.98s
277:	learn: 159.6790039	total: 2.47s	remaining: 1.97s
278:	learn: 159.5265309	total: 2.48s	remaining: 1.96s
279:	learn: 159.4693157	total: 2.49s	remaining: 1.95s
280:	learn: 159.3858140	total: 2.5s	remaining: 1.95s
281:	learn: 159.1767099	total: 2.5s	remaining: 1.94s
282:	learn: 159.0689153	total: 2.51s	remaining: 1.93s
283:	learn: 158.9709754	total: 2.52s	remaining: 1.92s
284:	learn: 158.7969900	total: 2.53s	remaining: 1.91s
285:	learn: 158.6854045	total: 2.54s	remaining: 1.9s
286:	learn: 158.5583962	total: 2.54s	remaining: 1.89s
287:	learn: 158.4762750	total: 2.55s	remaining: 1.88s
288:	learn: 158.3623632	total: 2.56s	remaining: 1.87s
289:	learn: 158.1452532	total: 2.57s	remaining: 1.86s
290:	learn: 158.0588783	total: 2.58s	remaining: 1.85s
291:	learn: 157.9290708	total: 2.59s	remaining: 1.84s
292:	learn: 157.8185437	total: 2.6s	remaining: 1.83s
293:	learn: 157.6921118	total: 2.6s	remaining: 1.82s
294:	learn: 157.6198211	total: 2.61s	remaining: 1.81s
295:	learn: 157.4978898	total: 2.62s	remaining: 1.8s
296:	learn: 157.3739695	total: 2.63s	remaining: 1.8s
297:	learn: 157.2047978	total: 2.64s	remaining: 1.79s
298:	learn: 156.9615357	total: 2.65s	remaining: 1.78s
299:	learn: 156.8676359	total: 2.65s	remaining: 1.77s
300:	learn: 156.6950564	total: 2.66s	remaining: 1.76s
301:	learn: 156.5823368	total: 2.67s	remaining: 1.75s
302:	learn: 156.4614276	total: 2.68s	remaining: 1.74s
303:	learn: 156.3877499	total: 2.69s	remaining: 1.73s
304:	learn: 156.2249570	total: 2.7s	remaining: 1.72s
305:	learn: 156.1844558	total: 2.71s	remaining: 1.72s
306:	learn: 156.1007915	total: 2.71s	remaining: 1.71s
307:	learn: 155.9873002	total: 2.72s	remaining: 1.7s
308:	learn: 155.8557793	total: 2.73s	remaining: 1.69s
309:	learn: 155.7554000	total: 2.74s	remaining: 1.68s
310:	learn: 155.6346957	total: 2.75s	remaining: 1.67s
311:	learn: 155.5094924	total: 2.76s	remaining: 1.66s
312:	learn: 155.3605833	total: 2.76s	remaining: 1.65s
313:	learn: 155.2551182	total: 2.77s	remaining: 1.64s
314:	learn: 155.1565131	total: 2.78s	remaining: 1.63s
315:	learn: 155.0503454	total: 2.79s	remaining: 1.62s
316:	learn: 154.9283583	total: 2.8s	remaining: 1.61s
317:	learn: 154.8275009	total: 2.81s	remaining: 1.61s
318:	learn: 154.7316330	total: 2.81s	remaining: 1.6s
319:	learn: 154.5999680	total: 2.82s	remaining: 1.59s
320:	learn: 154.4791097	total: 2.83s	remaining: 1.58s
321:	learn: 154.4006729	total: 2.84s	remaining: 1.57s
322:	learn: 154.3008294	total: 2.85s	remaining: 1.56s
323:	learn: 154.1143081	total: 2.86s	remaining: 1.55s
324:	learn: 154.0410611	total: 2.87s	remaining: 1.54s
325:	learn: 153.9486380	total: 2.87s	remaining: 1.53s
326:	learn: 153.8259619	total: 2.88s	remaining: 1.52s
327:	learn: 153.7111806	total: 2.89s	remaining: 1.52s
328:	learn: 153.5872853	total: 2.9s	remaining: 1.51s
329:	learn: 153.4631873	total: 2.91s	remaining: 1.5s
330:	learn: 153.3562838	total: 2.92s	remaining: 1.49s
331:	learn: 153.2911153	total: 2.92s	remaining: 1.48s
332:	learn: 153.2245851	total: 2.93s	remaining: 1.47s
333:	learn: 153.0628362	total: 2.94s	remaining: 1.46s
334:	learn: 152.9775472	total: 2.95s	remaining: 1.45s
335:	learn: 152.8865267	total: 2.96s	remaining: 1.44s
336:	learn: 152.7794822	total: 2.97s	remaining: 1.44s
337:	learn: 152.7153553	total: 2.98s	remaining: 1.43s
338:	learn: 152.6349177	total: 2.98s	remaining: 1.42s
339:	learn: 152.5311785	total: 2.99s	remaining: 1.41s
340:	learn: 152.4345399	total: 3s	remaining: 1.4s
341:	learn: 152.3523262	total: 3.01s	remaining: 1.39s
342:	learn: 152.2287633	total: 3.02s	remaining: 1.38s
343:	learn: 152.1348260	total: 3.02s	remaining: 1.37s
344:	learn: 151.9900137	total: 3.03s	remaining: 1.36s
345:	learn: 151.8653596	total: 3.04s	remaining: 1.35s
346:	learn: 151.7693811	total: 3.05s	remaining: 1.34s
347:	learn: 151.6483825	total: 3.06s	remaining: 1.34s
348:	learn: 151.5005080	total: 3.07s	remaining: 1.33s
349:	learn: 151.3519550	total: 3.08s	remaining: 1.32s
350:	learn: 151.2662405	total: 3.09s	remaining: 1.31s
351:	learn: 151.1907222	total: 3.09s	remaining: 1.3s
352:	learn: 151.0418011	total: 3.1s	remaining: 1.29s
353:	learn: 150.9426191	total: 3.11s	remaining: 1.28s
354:	learn: 150.8006391	total: 3.12s	remaining: 1.27s
355:	learn: 150.6780133	total: 3.13s	remaining: 1.26s
356:	learn: 150.5807423	total: 3.14s	remaining: 1.26s
357:	learn: 150.4689066	total: 3.14s	remaining: 1.25s
358:	learn: 150.3185284	total: 3.15s	remaining: 1.24s
359:	learn: 150.2110274	total: 3.16s	remaining: 1.23s
360:	learn: 150.1135994	total: 3.17s	remaining: 1.22s
361:	learn: 149.9522402	total: 3.18s	remaining: 1.21s
362:	learn: 149.8502658	total: 3.19s	remaining: 1.2s
363:	learn: 149.7304262	total: 3.2s	remaining: 1.19s
364:	learn: 149.6160163	total: 3.2s	remaining: 1.19s
365:	learn: 149.5305046	total: 3.21s	remaining: 1.18s
366:	learn: 149.4790146	total: 3.22s	remaining: 1.17s
367:	learn: 149.3827595	total: 3.23s	remaining: 1.16s
368:	learn: 149.2463098	total: 3.24s	remaining: 1.15s
369:	learn: 149.0865457	total: 3.25s	remaining: 1.14s
370:	learn: 148.9522577	total: 3.25s	remaining: 1.13s
371:	learn: 148.8018561	total: 3.26s	remaining: 1.12s
372:	learn: 148.6849295	total: 3.27s	remaining: 1.11s

In [19]:
metrics_average_bill = pd.concat([ridge_metrics_average_bill, knn_metrics_average_bill, rf_metrics_average_bill, catboost_metrics_average_bill, mlp_metrics_average_bill], axis=0)
metrics_average_bill

  Целевая переменная           Модель        RMSE         MAE
0        Средний чек  RidgeRegression  215.383689  161.289115
0        Средний чек              KNN  160.983053   99.129364
0        Средний чек     RandomForest   93.727114   54.420618
0        Средний чек         CATBOOST  147.282291  110.115302
0        Средний чек              MLP  121.620000   89.130000

In [26]:
fig = px.bar(
    metrics_average_bill.sort_values(['RMSE', 'MAE']),
    x='Модель',
    y=['RMSE', 'MAE'],
    barmode='group',
    title='Результаты функционала ошибок для предсказания среднего чека'
)

fig.show()