In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler

In [8]:
!pip install python-calamine

Collecting python-calamine
  Downloading python_calamine-0.6.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.1 kB)
Downloading python_calamine-0.6.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (935 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 935.1/935.1 kB 4.3 MB/s eta 0:00:00
Installing collected packages: python-calamine
Successfully installed python-calamine-0.6.2

In [9]:
df = pd.read_excel('Х5.xlsx', engine = 'calamine')

In [34]:
df

,new_id,Месяц,Трафик,Средний чек,"Дата открытия, категориальный","Торговая площадь, категориальный",Населенный пункт,Регион,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Маркетплейсы, доставки, постаматы (100 м)",Медицинские уч. и аптеки (300 м),Школы (300 м),Остановки (300 м),Продуктовые магазины (500 м),Пятерочки (500 м)
0,0,10,59662,823.060390,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.900,200.333333,0,6,0,0,2,0
1,0,5,56674,859.361975,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.900,200.333333,0,6,0,0,2,0
2,0,1,51488,763.937766,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.900,200.333333,0,6,0,0,2,0
3,0,6,56693,836.362309,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.900,200.333333,0,6,0,0,2,0
4,0,7,58128,845.257709,Средний по возрасту,Средний,Кавказская ст-ца,Краснодарский край,10177,608,76.900,200.333333,0,6,0,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256718,21742,10,51676,1167.101083,Новый,Средний,Октябрьский рп,Волгоградская обл,6071,262,125.375,243.333333,1,1,0,0,1,0
256719,21742,11,51516,1252.914118,Новый,Средний,Октябрьский рп,Волгоградская обл,6071,262,125.375,243.333333,1,1,0,0,1,0
256720,21742,9,49593,1130.823998,Новый,Средний,Октябрьский рп,Волгоградская обл,6071,262,125.375,243.333333,1,1,0,0,1,0
256721,21742,12,52115,1461.929305,Новый,Средний,Октябрьский рп,Волгоградская обл,6071,262,125.375,243.333333,1,1,0,0,1,0
256722,21742,8,47294,1087.924639,Новый,Средний,Октябрьский рп,Волгоградская обл,6071,262,125.375,243.333333,1,1,0,0,1,0

In [36]:
out = pd.DataFrame()

In [37]:
out['month_sin'] = np.sin(2 * np.pi * df['Месяц'] / 12)
out['month_cos'] = np.cos(2 * np.pi * df['Месяц'] / 12)

In [38]:
rs = RobustScaler()
out[['Численность населения', 'Количество домохозяйств', 'Трафик пеший, в час', 'Трафик авто, в час']] = rs.fit_transform(df[['Численность населения', 'Количество домохозяйств', 'Трафик пеший, в час', 'Трафик авто, в час']])

In [39]:
dmms = pd.get_dummies(df[['Дата открытия, категориальный', 'Торговая площадь, категориальный']]).astype(int)
out = pd.concat([out, dmms], axis = 1)

In [40]:
out

,month_sin,month_cos,Численность населения,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
0,-8.660254e-01,5.000000e-01,-0.182274,-0.533564,-0.543060,0.321416,0,0,1,0,0,0,1
1,5.000000e-01,-8.660254e-01,-0.182274,-0.533564,-0.543060,0.321416,0,0,1,0,0,0,1
2,5.000000e-01,8.660254e-01,-0.182274,-0.533564,-0.543060,0.321416,0,0,1,0,0,0,1
3,1.224647e-16,-1.000000e+00,-0.182274,-0.533564,-0.543060,0.321416,0,0,1,0,0,0,1
4,-5.000000e-01,-8.660254e-01,-0.182274,-0.533564,-0.543060,0.321416,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
256718,-8.660254e-01,5.000000e-01,-0.188420,-0.608489,0.067017,0.549735,1,0,0,0,0,0,1
256719,-5.000000e-01,8.660254e-01,-0.188420,-0.608489,0.067017,0.549735,1,0,0,0,0,0,1
256720,-1.000000e+00,-1.836970e-16,-0.188420,-0.608489,0.067017,0.549735,1,0,0,0,0,0,1
256721,-2.449294e-16,1.000000e+00,-0.188420,-0.608489,0.067017,0.549735,1,0,0,0,0,0,1
256722,-8.660254e-01,-5.000000e-01,-0.188420,-0.608489,0.067017,0.549735,1,0,0,0,0,0,1

In [26]:
df_cut_average_bill = pd.read_excel('df_cut_average_bill.xlsx')

In [27]:
df_cut_traffic = pd.read_excel('df_cut_traffic.xlsx')

In [42]:
traffic_final = pd.concat([df_cut_traffic.reset_index(drop = True), out.reset_index(drop = True)], axis = 1)
bill_final = pd.concat([df_cut_average_bill.reset_index(drop = True), out.reset_index(drop = True)], axis = 1)

In [43]:
traffic_final.head(10)

,new_id,Трафик,Средний чек,Населенный пункт_fold_traffic,Регион_fold_traffic,pca_1,pca_2,pca_3,pca_4,month_sin,...,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
0,0,59662,823.060390,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,-8.660254e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
1,0,56674,859.361975,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,5.000000e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
2,0,51488,763.937766,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,5.000000e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
3,0,56693,836.362309,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,1.224647e-16,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
4,0,58128,845.257709,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,-5.000000e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
5,0,59476,1011.737175,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,-2.449294e-16,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
6,0,55856,778.168307,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,-1.000000e+00,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
7,0,52602,783.000250,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,8.660254e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
8,0,54706,812.169894,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,1.000000e+00,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1
9,0,57311,866.303037,57260.693459,57482.03329,-0.5003,0.127879,0.066435,-1.215406,-5.000000e-01,...,-0.533564,-0.54306,0.321416,0,0,1,0,0,0,1

In [46]:
bill_final.sample(10)

,new_id,Трафик,Средний чек,Населенный пункт_fold_average_bill,Регион_fold_average_bill,pca_1,pca_2,pca_3,pca_4,month_sin,...,Количество домохозяйств,"Трафик пеший, в час","Трафик авто, в час","Дата открытия, категориальный_Новый","Дата открытия, категориальный_Открыт давно","Дата открытия, категориальный_Средний по возрасту","Торговая площадь, категориальный_Большой","Торговая площадь, категориальный_Маленький","Торговая площадь, категориальный_Очень большой","Торговая площадь, категориальный_Средний"
1098,91,65232,885.119931,779.633615,849.417941,2.404629,0.560981,-1.435531,-0.028286,0.866025,...,0.476397,0.383750,0.216637,0,0,1,0,1,0,0
168368,14047,72921,1452.150724,967.323147,785.259117,-1.464945,0.590828,-0.504012,0.648120,-0.500000,...,-0.636206,-0.271215,2.809911,0,0,1,0,0,0,1
187597,15655,73138,1297.836323,1234.673775,1241.172722,3.026386,-0.801908,1.608921,-0.275556,-0.500000,...,1.873322,-0.083545,-0.584526,1,0,0,0,0,0,1
23836,1988,67301,1456.242809,1300.078219,1300.078219,0.738249,1.435486,0.886360,-1.070721,0.866025,...,0.762884,0.235137,-0.031733,0,0,1,0,0,1,0
144290,12037,43980,582.917721,767.743906,766.149271,2.386054,0.188663,-1.011936,-1.131136,0.500000,...,0.982027,0.118562,0.557359,0,0,1,0,0,0,1
129571,10809,58036,792.621869,786.065766,1086.719137,0.486181,-1.656827,-0.688016,0.205084,-1.000000,...,0.093547,-0.122288,0.333584,0,0,1,0,0,0,1
142152,11859,49740,869.883014,1321.661227,1244.534393,-1.745927,0.009434,-0.087511,0.023466,0.500000,...,-0.409485,0.634933,1.323850,0,0,1,0,1,0,0
65552,5467,45565,716.724775,1203.481352,826.757140,-1.202838,-0.161810,-0.182682,-0.069983,-0.500000,...,-0.484192,0.621776,1.218319,0,0,1,0,1,0,0
182239,15207,60468,1203.984605,965.988700,738.228702,-1.262296,0.680785,-0.505233,0.488153,0.500000,...,-0.551537,-1.510877,-0.742301,1,0,0,0,0,0,1
130834,10914,65227,1100.276777,965.988700,1236.299752,-1.200040,0.704626,0.002863,-0.819341,1.000000,...,-0.440883,-1.017530,1.179823,0,0,1,0,1,0,0

In [48]:
traffic_final.to_excel('traffic_final.xlsx', index = False)

In [49]:
bill_final.to_excel('bill_final.xlsx', index = False)